# Generated by Django 3.0.4 on 2020-03-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20200323_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='janta',
            name='dp',
            field=models.ImageField(default='profile photo', upload_to='profile pictures/'),
        ),
    ]
